---
name: stratisd CI on ubuntu

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
      - 'README_tests.md'
      - 'tests/**'

  workflow_dispatch:

jobs:
  checks:
    strategy:
      matrix:
        include:
          - task: make -f Makefile clippy
            toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: clippy
          - task: PROFILEDIR=debug make -f Makefile build
            toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
          - task: PROFILEDIR=debug make -f Makefile build-min
            toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
          - task: PROFILEDIR=debug make -f Makefile build-extras
            toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
          - task: make -f Makefile docs-travis
            toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
          - task: make -f Makefile test
            toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
          - task: make -f Makefile build
            toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
          - task: make -f Makefile build-min
            toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:jammy
      options: --privileged -v /dev:/dev
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for Ubuntu
        run: apt-get -q update
      - name: Install dependencies for Ubuntu
        run: >
          DEBIAN_FRONTEND=noninteractive
          apt-get install -y
          clang
          curl
          libblkid-dev
          libcryptsetup-dev
          libdbus-1-dev
          libdevmapper-dev
          libsystemd-dev
          libudev-dev
          make
          thin-provisioning-tools
      - uses: actions-rs/toolchain@v1
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: ${{ matrix.task }}

  # TESTS WITH UDEV
  checks_with_udev:
    strategy:
      matrix:
        include:
          - task: RUST_LOG=stratisd=debug make -f Makefile test-loop
            toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            components: cargo
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Stop host udevd
        run: |
          sudo systemctl stop systemd-udevd
          sudo systemctl disable systemd-udevd-kernel.socket
          sudo systemctl disable systemd-udevd-control.socket
      - uses: bmr-cymru/fedora-stratisd-composite-action@v1
        with:
          image: ubuntu:jammy
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          task: ${{ matrix.task }}
          deps: >
            apt-get -q update;
            apt-get install -y
            asciidoc
            clang
            curl
            libblkid-dev
            libcryptsetup-dev
            libdbus-1-dev
            libdevmapper-dev
            libsystemd-dev
            libudev-dev
            make
            systemd
            thin-provisioning-tools
            udev
            xfsprogs
